aliases:
  - "enchanter"
  - "enchant"
  - "mcenchant"

blacklisted-worlds:
  - "world_spawn"
  - "lobby"

enchant-remover:
  enabled: true
  interaction-block: "nexo:unenchanter_block"
  timeout-seconds: 10

  item-display:
    scale: 0.8
    y-offset: 1.1

  brush:
    required-swipes: 5
    particle-effect: "CRIT"
    sound-effect: "ITEM_BRUSH_BRUSHING_SAND"

  new-success-rates:
    min: 40
    max: 75

sounds:
  error: "minelush.gui.weapon_ui_sound"
  success: "minelush.gui.upgrade"
  open-gui: "minelush.gui.button_click_1"

enchant-per-item: 5

ignored-materials:
  - "BEDROCK"
  - "BARRIER"
  - "END_PORTAL_FRAME"
  - "END_PORTAL"
  - "NETHER_PORTAL"
  - "SPAWNER"
  - "CHEST"
  - "ENDER_CHEST"
  - "TRAPPED_CHEST"
  - "SHULKER_BOX"
  - "NOTE_BLOCK"
  - "WHITE_SHULKER_BOX"
  - "ORANGE_SHULKER_BOX"
  - "MAGENTA_SHULKER_BOX"
  - "LIGHT_BLUE_SHULKER_BOX"
  - "YELLOW_SHULKER_BOX"
  - "LIME_SHULKER_BOX"
  - "PINK_SHULKER_BOX"
  - "GRAY_SHULKER_BOX"
  - "LIGHT_GRAY_SHULKER_BOX"
  - "CYAN_SHULKER_BOX"
  - "PURPLE_SHULKER_BOX"
  - "BLUE_SHULKER_BOX"
  - "BROWN_SHULKER_BOX"
  - "GREEN_SHULKER_BOX"
  - "RED_SHULKER_BOX"
  - "BLACK_SHULKER_BOX"
  - "BARREL"
  - "HOPPER"
  - "DROPPER"
  - "DISPENSER"
  - "FURNACE"
  - "BLAST_FURNACE"
  - "SMOKER"
  - "BREWING_STAND"
  - "ENCHANTING_TABLE"
  - "ANVIL"
  - "CHIPPED_ANVIL"
  - "DAMAGED_ANVIL"
  - "SIGN"
  - "OAK_SIGN"
  - "SPRUCE_SIGN"
  - "BIRCH_SIGN"
  - "JUNGLE_SIGN"
  - "ACACIA_SIGN"
  - "DARK_OAK_SIGN"
  - "CRIMSON_SIGN"
  - "WARPED_SIGN"
  - "OAK_WALL_SIGN"
  - "SPRUCE_WALL_SIGN"
  - "BIRCH_WALL_SIGN"
  - "JUNGLE_WALL_SIGN"
  - "ACACIA_WALL_SIGN"
  - "DARK_OAK_WALL_SIGN"
  - "CRIMSON_WALL_SIGN"
  - "WARPED_WALL_SIGN"

revealed-book-item:
  material: "PAPER"
  modeldata: 254
  name: "{name} &8[&#94A3B8{level}&8]"
  lore:
    - '&8- ᴇɴᴄʜᴀɴᴛ'
    - ''
    - ' &f<glyph:chat_information:colorable> &#4595DFInformáció'
    - ' &f{description}'
    - ''
    - ' &#4FDB75☑ &fSiker ráta: &#4FDB75{success}%'
    - ' &#C81035☒ &fBukás ráta: &#C81035{destroy}%'
    - ' &#14ABB1☐ &fAlkalmazható: &#14ABB1{applies}'
    - ''
    - '&f<glyph:emoji_mouse_middle:colorable> &#CACACAʜ<glyph:uhosszu:colorable>ᴢᴅ ʀ<glyph:ahosszu:colorable> ᴀᴢ ᴀʟᴋᴀʟᴍᴀᴢ<glyph:ahosszu:colorable>ꜱʜᴏᴢ'

mysterious-book-item:
  material: "BOOK"
  name: "{categoryColor}{categoryName} &fKönyv"
  lore:
    - '&8- ᴇɴᴄʜᴀɴᴛ'
    - ''
    - ' &f<glyph:chat_information:colorable> &#4595DFInformáció'
    - ' &f&kdsagsdajgjsjgss'
    - ' &f&kghoawikdsfkhjsa'
    - ''
    - ' &#4FDB75☑ &fSiker ráta: &#4FDB75&ksad%'
    - ' &#C81035☒ &fBukás ráta: &#C81035&ksud%'
    - ' &#14ABB1☐ &fAlkalmazható: &#14ABB1&kfkskasksa'
    - ''
    - '&f<glyph:emoji_mouse_right:colorable> &#CACACAᴊᴏʙʙ ᴋᴀᴛᴛ ᴀ ꜰᴇʟꜰᴇᴅᴇᴢ<glyph:ehosszu:colorable>ꜱʜᴇᴢ!'

dust-item:
  material: "SUGAR"
  name: "{categoryColor}{categoryName} &fJavító Por"
  lore:
    - '&8- ᴘᴏʀ'
    - ''
    - ' &f<glyph:chat_information:colorable> &#4595DFInformáció'
    - ' &fAdd oda Málnának, hogy'
    - ' &ffeljavítsd vele a kedvenc'
    - " &fenchant könyvedre!"
    - ''
    - ' &#4FDB75☑ &fJavítás: &#4FDB75{repair}%'

version: '1'